CREATE TABLE `states`
(
	`id` CHAR(2) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`enabled` BOOLEAN NOT NULL
	PRIMARY KEY (`id`)
);

INSERT INTO `states` (`id`,`name`) VALUES
	('AL','Alabama',1),
	('AK','Alaska',1),
	('AS','American Samoa',1),
	('AZ','Arizona',1),
	('AR','Arkansas',1),
	('CA','California',1),
	('CO','Colorado',1),
	('CT','Connecticut',1),
	('DE','Delaware',1),
	('DC','District Of Columbia',1),
	('FM','Federated States Of Micronesia',1),
	('FL','Florida',1),
	('GA','Georgia',1),
	('GU','Guam',1),
	('HI','Hawaii',1),
	('ID','Idaho',1),
	('IL','Illinois',1),
	('IN','Indiana',1),
	('IA','Iowa',1),
	('KS','Kansas',1),
	('KY','Kentucky',1),
	('LA','Louisiana',1),
	('ME','Maine',1),
	('MH','Marshall Islands',1),
	('MD','Maryland',1),
	('MA','Massachusetts',1),
	('MI','Michigan',1),
	('MN','Minnesota',1),
	('MS','Mississippi',1),
	('MO','Missouri',1),
	('MT','Montana',1),
	('NE','Nebraska',1),
	('NV','Nevada',1),
	('NH','New Hampshire',1),
	('NJ','New Jersey',1),
	('NM','New Mexico',1),
	('NY','New York',1),
	('NC','North Carolina',1),
	('ND','North Dakota',1),
	('MP','Northern Mariana Islands',1),
	('OH','Ohio',1),
	('OK','Oklahoma',1),
	('OR','Oregon',1),
	('PW','Palau',1),
	('PA','Pennsylvania',1),
	('PR','Puerto Rico',1),
	('RI','Rhode Island',1),
	('SC','South Carolina',1),
	('SD','South Dakota',1),
	('TN','Tennessee',1),
	('TX','Texas',1),
	('UT','Utah',1),
	('VT','Vermont',1),
	('VI','Virgin Islands',1),
	('VA','Virginia',1),
	('WA','Washington',1),
	('WV','West Virginia',1),
	('WI','Wisconsin',1),
	('WY','Wyoming',1),
	('AE','Armed Forces Africa',1),
	('AA','Armed Forces Americas (Except Canada)',1),
	('AE','Armed Forces Canada',1),
	('AE','Armed Forces Europe',1),
	('AE','Armed Forces Middle East',1),
	('AP','Armed Forces Pacific',1);